### ISSUE TITLE
iOs animations stop working

### ISSUE THREAD

**Issue by ConnorMusic** [olddonkey/ShadowImageView#9] opened 2017-05-26 09:30 UTC
When I use it sometimes ios animations stop working. I revised my code but its correct. I try to do the same without your pod and works fine.
I think that it is cause you are updating the UI without using the `DispatchQueue.main.async`. Please revised and tell me something cause your project its incredible. Thanks

**Comment by olddonkey** [comment] 2017-05-26 15:45
You are right, I forget to dispatch to main thread, I will update it today. Thanks so much for let me know

**Comment by olddonkey** [comment] 2017-05-27 07:21
Hi, I have updated the project, using CALayer instead of UIView, please test if the problem exist or not.

Let me know if the problem is still there.

**Comment by olddonkey** [comment] 2017-05-27 07:22
I will close this for now, if you have problem, feel free to reopen this.

**Closed as completed by olddonkey** 2017-05-27 07:22 UTC
Labels: bug
